#!/usr/bin/env bash

source $(dirname "$0")/common

load_exp()
{
  drop_caches

  prepare_log load

  iotrace_wrapped ./dbtest1.out api ${sys[@]} \
    rgen shuffle 0 ${maxk} pass  1 1 $((${fill} / 200)) 200 0   3  s ${klen} ${vlen} \
    > >(tee ${sout}) 2> >(tee ${serr} >&2)
}

prep "$@"

load_exp

