#!/usr/bin/env bash

set -e

source $(dirname "$0")/common

write_exp()
{
  drop_caches

  prepare_log load

  biosnoop_wrapped smartctl_wrapped ./dbtest1.out api ${sys[@]} \
    rgen skipu   0 ${maxk} ${inc} pass  1 1 $((${fill} / 200)) 200 0   3  s ${klen} ${vlen} \
    > >(tee ${sout}) 2> >(tee ${serr} >&2)
}

set_args "$@"

make_executables

set_drive

write_exp

