#!/usr/bin/env bash

source $(dirname "$0")/common

load_exp()
{
  drop_caches

  prepare_log load

  iotrace_wrapped ./dbtest.out api ${sys[@]} \
    rgen shuffle 0 ${maxk} pass  1 1 $((${fill} / 200)) 200 0   3  s ${klen} ${vlen} \
    > >(tee ${sout}) 2> >(tee ${serr} >&2)

  parse_dbtest_csv
}

prep "$@"

if [ -d ${sys[1]} ]; then
  if [ "$(ls -A ${sys[1]})" ]; then
    echo "Loading experiments are supposed to run on an empty folder."
    read -p  "${sys[1]} is not empty, do you want to continue [N/y]?" yesno

    case $yesno in
    [Yy]*)
      ;;
    *)
      echo Exiting
      exit
      ;;
    esac
  fi
fi

load_exp

collect_log load

