#!/usr/bin/env bash

set -e

if [ $# -lt 1 ]; then
  echo "usage
  $0 -k <key file>
                       -n <number of keys>
                       -v <value length>
                       -q <number of queries>
                       -r <uniform/zipfian/unizipf>
                       -m <mixed/existing/non-existing>"
  exit 1
fi

make msstio.out

./msstio.out $*

foldername="trace-$(date +'%Y-%m-%d-%H-%M-%S')"
mkdir ${foldername}

echo "Traces saved to folder ${foldername}"

mv *.trace ${foldername}

mv *.meta ${foldername}

$(dirname "$0")/sim_csv.sh ${foldername}

