#!/usr/bin/env bash

source $(dirname "$0")/common

zipfian_range_read_exp()
{
  prepare_log zipf-read-seek

  local nscan=0
  iotrace_wrapped ./dbtest1.out api ${sys[@]} \
    rgen unizipf 0 ${maxk} 1000 pass  4 0 600 10  1   3  n ${klen} ${nscan} \
    > >(tee ${sout}) 2> >(tee ${serr} >&2)
}

zipfian_point_read_exp()
{
  prepare_log zipf-read-probe

  local nscan=0
  iotrace_wrapped ./dbtest1.out api ${sys[@]} \
    rgen unizipf 0 ${maxk} 1000 pass  4 0 600 10  1   3  p ${klen} ${nscan} \
    > >(tee ${sout}) 2> >(tee ${serr} >&2)
}

range_read_exp()
{
  prepare_log random-read-seek

  local nscan=0
  iotrace_wrapped ./dbtest1.out api ${sys[@]} \
    rgen uniform 0 ${maxk} pass  4 0 600 5  1   3  n ${klen} ${nscan} \
    > >(tee ${sout}) 2> >(tee ${serr} >&2)
}

point_read_exp()
{
  prepare_log random-read-probe

  local nscan=0
  iotrace_wrapped ./dbtest1.out api ${sys[@]} \
    rgen uniform 0 ${maxk} pass  4 0 600 5  1   3  p ${klen} ${nscan} \
    > >(tee ${sout}) 2> >(tee ${serr} >&2)
}

prep "$@"

warmup

range_read_exp

point_read_exp

zipfian_range_read_exp

zipfian_point_read_exp

