#!/usr/bin/env bash

set -e

sudo apt-get -y update
sudo apt-get -y upgrade

# dependencies for disco
sudo apt-get -y install sudo git build-essential cmake clang python3 parallel python-is-python3 \
  python3-pip libcairo2-dev pkg-config python3-dev

# dependencies for RocksDB
sudo apt-get -y install libgflags-dev libsnappy-dev zlib1g-dev libbz2-dev liblz4-dev libzstd-dev

# dependencies for bcc
sudo apt-get install -y zip bison build-essential cmake flex git libedit-dev \
  libllvm14 llvm-14-dev libclang-14-dev python3 zlib1g-dev libelf-dev libfl-dev python3-setuptools \
  liblzma-dev libdebuginfod-dev arping netperf iperf

# build bcc
cd
git clone https://github.com/iovisor/bcc.git
cd bcc
git checkout v0.30.0
git submodule update
mkdir build; cd build
cmake ..
make -j
sudo make install
cmake -DPYTHON_CMD=python3 .. # build python3 binding
pushd src/python/
make -j
sudo make install
popd

# build rocksdb
cd
git clone https://github.com/facebook/rocksdb.git
cd ~/rocksdb
git checkout v8.10.0
make -j static_lib
cp ./librocksdb.a ~/disco
mkdir -p ~/disco/include/rocksdb
cp ~/rocksdb/include/rocksdb/c.h ~/disco/include/rocksdb

# plotting dependencies
cd ~/disco
pip install -r ./requirements.txt
